<?php

/**
 *
 * @file
 * Primary module hooks for Habeuk custom module.
 */
/**
 * Implements hook_theme().
 */
function habeuk_custom_theme() {
  $hooks = [];
  $hooks['hbktabs_order_site'] = [
    'variables' => [
      'tabs' => [],
      'id_tabs' => NULL
    ]
  ];
  return $hooks;
}

/**
 * Implements hook_page_attachments().
 */
function habeuk_custom_page_attachments(array &$attachments) {
  $attachments['#attached']['html_head'][] = [
    [
      '#tag' => 'meta',
      '#attributes' => [
        'property' => 'og:logo',
        'content' => 'https://habeuk.com/sites/default/files/styles/medium/public/2024-11/hlogo.png'
      ]
    ],
    'og_logo'
  ];
}

/**
 * Implements hook_js_alter().
 */
// function habeuk_custom_js_alter(&$javascript) {
// // Liste des fichiers à exclure du preprocessing
// $excluded_files = [];

// foreach ($javascript as &$js) {
// foreach ($excluded_files as $excluded_file) {
// if (strpos($js['data'], $excluded_file) !== FALSE) {
// $js['preprocess'] = FALSE;
// \Drupal::messenger()->addStatus(t('Fichier exclu du preprocessing: @file', [
// '@file' => $js['data']
// ]));
// break;
// }
// }
// }
// }

/**
 * Implement hook_form_alter
 * Permet d'alterer les champs.
 */
function habeuk_custom_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $context) {
  if (!empty($form['#webform_id'])) {
    if (\Drupal::currentUser()->id() == 0) {
      // Doit correspondre à une action créée dans l'interface admin
      $action_id = 'hbk_validation_des_webforms';
      // 2. Ajouter le champ CAPTCHA
      $captcha = [
        '#type' => 'captcha',
        '#captcha_type' => 'recaptcha_v3/' . $action_id
      ];
      // 3. Placement dans le formulaire
      if (!empty($form['elements'])) {
        $form['elements']['actions']['#weight'] = 10;
        $form['elements']['captcha'] = $captcha;
      }
      else {
        $form['actions']['#weight'] = 10;
        $form['captcha'] = $captcha;
      }
    }
  }
}
